-- Ubuntu 3.0 — v0.2 database schema
--
-- One database (default name: ubuntu_me) on the same MySQL server as Moodle.
-- All IDs are UUIDs generated by the client. The server stamps server_updated_at
-- on every write; clients adopt that as the source of truth on the next sync.

SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- ============================================================
--  users + auth
-- ============================================================

CREATE TABLE IF NOT EXISTS users (
  id              CHAR(36)        NOT NULL,
  email           VARCHAR(254)    NOT NULL,          -- unique identifier (login + invites)
  phone           VARCHAR(50)     NULL,               -- v0.3.5f: person's phone (not unique)
  password_hash   VARCHAR(255)    NOT NULL,
  name            VARCHAR(120)    NOT NULL,          -- derived from first_name + ' ' + last_name (legacy)
  first_name      VARCHAR(80)     NOT NULL,          -- v0.3.4: required at creation
  last_name       VARCHAR(80)     NOT NULL DEFAULT '',
  sex             CHAR(1)         NULL,               -- v0.3.5e: demographics on the person, not on the course
  age_range       VARCHAR(20)     NULL,
  role            ENUM('trainer','admin','trainee') NOT NULL DEFAULT 'trainer',
  language        CHAR(2)         NOT NULL DEFAULT 'fr',
  must_change_password TINYINT(1) NOT NULL DEFAULT 0,
  created_at      DATETIME        NOT NULL,
  updated_at      DATETIME        NOT NULL,
  last_login_at   DATETIME        NULL,
  disabled_at     DATETIME        NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_users_email (email),
  KEY idx_users_disabled (disabled_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS auth_sessions (
  id              CHAR(36)        NOT NULL,
  user_id         CHAR(36)        NOT NULL,
  token_hash      CHAR(64)        NOT NULL,   -- SHA-256 of the bearer token
  created_at      DATETIME        NOT NULL,
  expires_at      DATETIME        NOT NULL,
  last_used_at    DATETIME        NOT NULL,
  user_agent      VARCHAR(255)    NULL,
  ip              VARCHAR(45)     NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_sessions_token (token_hash),
  KEY idx_sessions_user (user_id),
  KEY idx_sessions_expires (expires_at),
  CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Phase B
CREATE TABLE IF NOT EXISTS password_resets (
  id              CHAR(36)        NOT NULL,
  user_id         CHAR(36)        NOT NULL,
  token_hash      CHAR(64)        NOT NULL,
  expires_at      DATETIME        NOT NULL,
  used_at         DATETIME        NULL,
  PRIMARY KEY (id),
  KEY idx_resets_user (user_id),
  KEY idx_resets_token (token_hash),
  CONSTRAINT fk_resets_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
--  domain entities
--  Each table mirrors the client shape and adds:
--    author_id            FK to users (server-set, never trusted from client)
--    client_updated_at    timestamp the client claims (informational)
--    server_updated_at    authoritative for sync (set by server on each write)
--    deleted_at           soft delete tombstone
-- ============================================================

CREATE TABLE IF NOT EXISTS cohorts (
  id                  CHAR(36)        NOT NULL,
  name                VARCHAR(255)    NOT NULL DEFAULT '',
  region              VARCHAR(120)    NULL,
  start_date          DATE            NULL,
  end_date            DATE            NULL,
  author_id           CHAR(36)        NULL,
  client_updated_at   DATETIME        NULL,
  server_updated_at   DATETIME        NOT NULL,
  created_at          DATETIME        NOT NULL,
  deleted_at          DATETIME        NULL,
  PRIMARY KEY (id),
  KEY idx_cohorts_server_updated (server_updated_at),
  KEY idx_cohorts_author (author_id),
  CONSTRAINT fk_cohorts_author FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS groups_ (
  id                  CHAR(36)        NOT NULL,
  cohort_id           CHAR(36)        NULL,
  name                VARCHAR(255)    NOT NULL DEFAULT '',
  facilitator         VARCHAR(255)    NULL,
  author_id           CHAR(36)        NULL,
  client_updated_at   DATETIME        NULL,
  server_updated_at   DATETIME        NOT NULL,
  created_at          DATETIME        NOT NULL,
  deleted_at          DATETIME        NULL,
  PRIMARY KEY (id),
  KEY idx_groups_cohort (cohort_id),
  KEY idx_groups_server_updated (server_updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- Note: groups_ (trailing underscore) avoids a reserved word in some MySQL versions.

CREATE TABLE IF NOT EXISTS participants (
  id                  CHAR(36)        NOT NULL,
  group_id            CHAR(36)        NULL,
  first_name          VARCHAR(120)    NOT NULL DEFAULT '',
  last_name           VARCHAR(120)    NULL,
  sex                 ENUM('F','M','NB') NULL,
  age_range           VARCHAR(16)     NULL,
  contact             VARCHAR(255)    NULL,
  author_id           CHAR(36)        NULL,
  client_updated_at   DATETIME        NULL,
  server_updated_at   DATETIME        NOT NULL,
  created_at          DATETIME        NOT NULL,
  deleted_at          DATETIME        NULL,
  PRIMARY KEY (id),
  KEY idx_participants_group (group_id),
  KEY idx_participants_server_updated (server_updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS training_sessions (
  id                  CHAR(36)        NOT NULL,
  group_id            CHAR(36)        NULL,
  date                DATE            NULL,
  theme               VARCHAR(255)    NULL,
  location            VARCHAR(255)    NULL,
  notes               TEXT            NULL,
  author_id           CHAR(36)        NULL,
  client_updated_at   DATETIME        NULL,
  server_updated_at   DATETIME        NOT NULL,
  created_at          DATETIME        NOT NULL,
  deleted_at          DATETIME        NULL,
  PRIMARY KEY (id),
  KEY idx_sessions_group (group_id),
  KEY idx_sessions_date (date),
  KEY idx_sessions_server_updated (server_updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS attendance (
  id                  CHAR(36)        NOT NULL,
  session_id          CHAR(36)        NULL,
  participant_id      CHAR(36)        NULL,
  present             TINYINT(1)      NOT NULL DEFAULT 0,
  author_id           CHAR(36)        NULL,
  client_updated_at   DATETIME        NULL,
  server_updated_at   DATETIME        NOT NULL,
  created_at          DATETIME        NOT NULL,
  deleted_at          DATETIME        NULL,
  PRIMARY KEY (id),
  KEY idx_attendance_session (session_id),
  KEY idx_attendance_participant (participant_id),
  KEY idx_attendance_server_updated (server_updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stories (
  id                  CHAR(36)        NOT NULL,
  session_id          CHAR(36)        NULL,
  participant_id      CHAR(36)        NULL,
  text                MEDIUMTEXT      NULL,
  consent             TINYINT(1)      NOT NULL DEFAULT 0,
  has_photo           TINYINT(1)      NOT NULL DEFAULT 0,   -- Phase B: actual bytes in story_media
  has_audio           TINYINT(1)      NOT NULL DEFAULT 0,
  author_id           CHAR(36)        NULL,
  client_updated_at   DATETIME        NULL,
  server_updated_at   DATETIME        NOT NULL,
  created_at          DATETIME        NOT NULL,
  deleted_at          DATETIME        NULL,
  PRIMARY KEY (id),
  KEY idx_stories_session (session_id),
  KEY idx_stories_participant (participant_id),
  KEY idx_stories_server_updated (server_updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Phase B: photo/audio bytes
CREATE TABLE IF NOT EXISTS story_media (
  id                  CHAR(36)        NOT NULL,
  story_id            CHAR(36)        NOT NULL,
  kind                ENUM('photo','audio') NOT NULL,
  mime                VARCHAR(80)     NOT NULL,
  size_bytes          INT UNSIGNED    NOT NULL,
  sha256              CHAR(64)        NOT NULL,
  storage_path        VARCHAR(500)    NOT NULL,        -- relative path on disk
  uploaded_at         DATETIME        NOT NULL,
  PRIMARY KEY (id),
  KEY idx_media_story (story_id),
  CONSTRAINT fk_media_story FOREIGN KEY (story_id) REFERENCES stories(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
